// Seed a small demo catalog so the assistant's retrieval returns real cards.
// Usage: node scripts/seedProducts.js
require("dotenv").config();
const mongoose = require("mongoose");
const connectDB = require("../db/mongodb");
const Product = require("../app/vendor/model/product.model");

// Real Benna category images (from the storefront's dealsConfig CDN assets).
const IMG = {
  "CEM-WHT-50": "https://static.wixstatic.com/media/b99a57_4a1f3f450aa9450f85515031b3f2cb6e~mv2.jpg",
  "CEM-OPC-50": "https://static.wixstatic.com/media/a3b8d7_2fdc5e16c9484b12a48207f662a594af~mv2.jpg",
  "TIL-POR-6060": "https://static.wixstatic.com/media/a3b8d7_037a45671d2e4d0d9e1789e3af24b975~mv2.jpg",
  "TIL-CER-2540": "https://static.wixstatic.com/media/b99a57_45894a2d055e4b1abf7dac779524e380~mv2.jpg",
  "PPR-32-PN20": "https://static.wixstatic.com/media/b99a57_f3959b698f954854a371fa7ad5911fd0~mv2.jpg",
  "PVC-110-6M": "https://static.wixstatic.com/media/a3b8d7_2354e24804134cc4b4dfefaf1188a813~mv2.jpg",
  "REB-12-G60": "https://static.wixstatic.com/media/b99a57_ee69ec4b62f94b1497e0fd89332226c4~mv2.png",
  "GYP-125-STD": "https://static.wixstatic.com/media/bcbfd4_b1b2defbea83487b9a16a9f49b28df12~mv2.jpg",
  "PNT-EMU-18": "https://static.wixstatic.com/media/b99a57_4a2e35e25a3144448e4f186cbf94cce8~mv2.jpg",
  "PNT-EXT-18": "https://static.wixstatic.com/media/b99a57_4a2e35e25a3144448e4f186cbf94cce8~mv2.jpg",
  "RMC-C30": "https://static.wixstatic.com/media/a3b8d7_1bcebaeb2f6b44d494d9644dec593035~mv2.jpg",
  "BLK-HOL-20": "https://static.wixstatic.com/media/a3b8d7_f4b3303df5d045a7991737cec2309c70~mv2.jpg",
  "SND-WSH-M3": "https://static.wixstatic.com/media/a3b8d7_fc0a2502e22d4c7abd58cfe997f42536~mv2.jpg",
  "AGG-20-M3": "https://static.wixstatic.com/media/a3b8d7_fe18a2794bf94861abfeea632feb5b00~mv2.jpg",
  "CBL-25-100": "https://static.wixstatic.com/media/a3b8d7_49d5c9d0d10e491fb0b9582f87752f34~mv2.jpg",
  "INS-RW-50": "https://static.wixstatic.com/media/a3b8d7_173c6a99f3e0428aabcb78afccbc2179~mv2.jpg",
  "WPR-BIT-4": "https://static.wixstatic.com/media/bcbfd4_ce51213ddee24f0d9c9d9d298467a9f8~mv2.jpg",
  "TLS-LAD-6": "https://static.wixstatic.com/media/b99a57_44da40bf6d5243d2a7cbea85247fe4c8~mv2.jpg",
  "SFT-HLM-W": "https://static.wixstatic.com/media/b99a57_319066a13a7144619ab810e12a62a562~mv2.jpg",
};

const DEMO = [
  {
    name: "White Cement 50kg Bag",
    nameArabic: "أسمنت أبيض 50 كجم",
    description: "Premium white Portland cement for finishing and decorative works.",
    brand: "Saudi Cement",
    sku: "CEM-WHT-50",
    collections: "Cement & Concrete",
    price: 28.5,
    unitOfMeasurement: "bag",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "white-cement-50kg-bag",
  },
  {
    name: "Porcelain Floor Tiles 60x60 Beige",
    nameArabic: "بلاط بورسلان أرضيات 60x60 بيج",
    description: "Polished porcelain floor tiles, slip resistant, per sqm pricing.",
    brand: "Rak Ceramics",
    sku: "TIL-POR-6060",
    collections: "Tiles & Flooring",
    price: 42,
    unitOfMeasurement: "sqm",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "porcelain-floor-tiles-60x60-beige",
  },
  {
    name: "PPR Pipe 32mm PN20",
    nameArabic: "ماسورة PPR مقاس 32 مم",
    description: "Green PPR pipe for hot and cold water, 4m length.",
    brand: "AquaTech",
    sku: "PPR-32-PN20",
    collections: "Plumbing",
    price: 18.75,
    unitOfMeasurement: "piece",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "ppr-pipe-32mm-pn20",
  },
  {
    name: "Steel Rebar 12mm Grade 60",
    nameArabic: "حديد تسليح 12 مم",
    description: "Deformed steel reinforcement bar, 12m length, per ton pricing.",
    brand: "SABIC Steel",
    sku: "REB-12-G60",
    collections: "Steel & Rebar",
    price: 2650,
    unitOfMeasurement: "ton",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "steel-rebar-12mm-grade-60",
  },
  {
    name: "Gypsum Board 12.5mm Standard",
    nameArabic: "لوح جبس 12.5 مم",
    description: "Standard gypsum plasterboard 1200x2400mm for partitions.",
    brand: "Knauf",
    sku: "GYP-125-STD",
    collections: "Boards & Drywall",
    price: 22,
    unitOfMeasurement: "sheet",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "gypsum-board-125mm-standard",
  },
  {
    name: "Interior Emulsion Paint White 18L",
    nameArabic: "دهان داخلي أبيض 18 لتر",
    description: "Washable interior emulsion paint, matt finish.",
    brand: "Jotun",
    sku: "PNT-EMU-18",
    collections: "Paints",
    price: 145,
    unitOfMeasurement: "bucket",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "interior-emulsion-paint-white-18l",
  },
  {
    name: "Ready Mix Concrete C30",
    nameArabic: "خرسانة جاهزة C30",
    description: "Ready-mixed concrete, 30 MPa, delivered to site. Quote only.",
    brand: "Saudi ReadyMix",
    sku: "RMC-C30",
    collections: "Cement & Concrete",
    price: 0,
    unitOfMeasurement: "m3",
    inventory: "InStock",
    isRFQ: true,
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "ready-mix-concrete-c30",
  },
  {
    name: "Ordinary Portland Cement OPC 50kg",
    nameArabic: "أسمنت بورتلاندي عادي 50 كجم",
    description: "Grey OPC cement for structural concrete and general construction.",
    brand: "Yamama Cement",
    sku: "CEM-OPC-50",
    collections: "Cement & Concrete",
    price: 14.25,
    unitOfMeasurement: "bag",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "opc-cement-50kg",
  },
  {
    name: "Concrete Hollow Block 20cm",
    nameArabic: "بلوك خرساني مفرغ 20 سم",
    description: "Standard hollow concrete block 20x20x40cm for walls.",
    brand: "Saudi Block Co",
    sku: "BLK-HOL-20",
    collections: "Blocks & Masonry",
    price: 2.4,
    unitOfMeasurement: "piece",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "concrete-hollow-block-20cm",
  },
  {
    name: "Washed Sand — Bulk",
    nameArabic: "رمل مغسول",
    description: "Washed construction sand, sold per cubic meter.",
    brand: "Riyadh Sands",
    sku: "SND-WSH-M3",
    collections: "Sand & Aggregate",
    price: 65,
    unitOfMeasurement: "m3",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "washed-sand-bulk",
  },
  {
    name: "Crushed Aggregate 20mm",
    nameArabic: "بحص مجروش 20 مم",
    description: "Crushed stone aggregate for concrete mixes, per cubic meter.",
    brand: "Riyadh Sands",
    sku: "AGG-20-M3",
    collections: "Sand & Aggregate",
    price: 78,
    unitOfMeasurement: "m3",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "crushed-aggregate-20mm",
  },
  {
    name: "Ceramic Wall Tiles 25x40 Glossy",
    nameArabic: "سيراميك جدران 25x40 لمّاع",
    description: "Glossy ceramic wall tiles for kitchens and bathrooms, per sqm.",
    brand: "Saudi Ceramics",
    sku: "TIL-CER-2540",
    collections: "Tiles & Flooring",
    price: 31,
    unitOfMeasurement: "sqm",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "ceramic-wall-tiles-25x40",
  },
  {
    name: "Copper Electrical Cable 2.5mm",
    nameArabic: "سلك كهربائي نحاس 2.5 مم",
    description: "Single-core copper cable 2.5mm², 100m roll, SASO approved.",
    brand: "Bahra Cables",
    sku: "CBL-25-100",
    collections: "Electrical",
    price: 189,
    unitOfMeasurement: "roll",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "copper-cable-2-5mm-100m",
  },
  {
    name: "PVC Drainage Pipe 110mm",
    nameArabic: "ماسورة صرف PVC مقاس 110 مم",
    description: "UPVC drainage pipe 110mm, 6m length, for waste lines.",
    brand: "National Pipe",
    sku: "PVC-110-6M",
    collections: "Plumbing",
    price: 34,
    unitOfMeasurement: "piece",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "pvc-drainage-pipe-110mm",
  },
  {
    name: "Rock Wool Insulation 50mm",
    nameArabic: "عزل صوف صخري 50 مم",
    description: "Rock wool thermal/acoustic insulation board 50mm, per sqm.",
    brand: "Rockwool",
    sku: "INS-RW-50",
    collections: "Insulation",
    price: 19.5,
    unitOfMeasurement: "sqm",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "rock-wool-insulation-50mm",
  },
  {
    name: "Bituminous Waterproofing Membrane 4mm",
    nameArabic: "لفائف عزل بيتومين 4 مم",
    description: "APP-modified bitumen membrane roll for roofs, 10 sqm coverage.",
    brand: "Sika",
    sku: "WPR-BIT-4",
    collections: "Waterproofing",
    price: 165,
    unitOfMeasurement: "roll",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "bitumen-membrane-4mm",
  },
  {
    name: "Aluminium Ladder 6-Step",
    nameArabic: "سلم ألمنيوم 6 درجات",
    description: "Foldable aluminium ladder, 6 steps, 150kg load rating.",
    brand: "Werner",
    sku: "TLS-LAD-6",
    collections: "Tools & Hardware",
    price: 210,
    unitOfMeasurement: "piece",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "aluminium-ladder-6-step",
  },
  {
    name: "Safety Helmet White",
    nameArabic: "خوذة سلامة بيضاء",
    description: "Industrial safety helmet, adjustable, SASO compliant.",
    brand: "3M",
    sku: "SFT-HLM-W",
    collections: "Safety Equipment",
    price: 28,
    unitOfMeasurement: "piece",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "safety-helmet-white",
  },
  {
    name: "Exterior Weatherproof Paint Beige 18L",
    nameArabic: "دهان خارجي بيج 18 لتر",
    description: "Weather-resistant exterior emulsion, UV stable, sandy beige.",
    brand: "Jotun",
    sku: "PNT-EXT-18",
    collections: "Paints",
    price: 178,
    unitOfMeasurement: "bucket",
    inventory: "InStock",
    productImageUrl: "",
    uploadedByVendorId: "demo-vendor",
    status: "approved",
    visible: true,
    uniqueProductSlug: "exterior-paint-beige-18l",
  },
];

(async () => {
  await connectDB();
  for (const p of DEMO) {
    const doc = { ...p, productImageUrl: IMG[p.sku] || p.productImageUrl || "" };
    await Product.updateOne({ sku: p.sku }, { $set: doc }, { upsert: true });
  }
  console.log(`Seeded ${DEMO.length} demo products.`);
  await mongoose.disconnect();
})();
